### ISSUE TITLE
failed pool:create prevents pool from being created again

### ISSUE THREAD

**Issue by jbardin** [litl/galaxy#206]
```
$ galaxy -env dev -pool marten pool:create
...
CreateStack Failed,...
....


$ galaxy -env dev pool
ENV  POOL    APPS
dev  rfmweb ...

$ galaxy -env dev -pool marten pool:create
Pool marten already exists
```

galaxy doesn't show that the stack exists, but it won't allow it to be created either

**Comment by jbardin** [comment]
The pool gets added to the `env/pools/*` redis set, but doesn't show in the list of pools.

**Comment by joeshaw** [comment]
It is lacking a matching `dev/pools/marten` key, which is why it doesn't appear in the list of pools.

**Comment by joeshaw** [comment]
I think this might be the same issue as #211, not 100% sure.

**Comment by joeshaw** [comment]
Nope, this is a different issue than #211, but somewhat related.

`ListPools()` looks in two different keyspaces.  One is `<env>/*/hosts/*/info`, which is automatically populated by commander when it starts up.  The second part of that path (the first `*`) is the pool name.  I don't know how that is populated.

The other keyspace is `<env>/pools/*`.  The literal key `<env>/pools/*` is ignored in this case (despite being a set that contains the names of all pools in that environment) and instead looks at `<env>/pools/<pool>`, which is populated only when an app is assigned to a pool.

I think a better way to go is to instead look the literal `<env>/pools/*` key and get a list of pools per environment from there.
