### ISSUE TITLE
Listing all apps takes too long

### ISSUE THREAD

**Issue by jbardin** [litl/galaxy#213]
Figure out why listing apps with galaxy with a remote redis instance takes so long. Even iterating over every possibly entry in the remote redis instance starting from `keys *` shouldn't account for this.

    $ time galaxy --registry redis://127.0.0.1:6379 app > /dev/null
    real	0m11.219s

**Comment by jbardin** [comment]
This may also be related to some general failures in galaxy. If commands are taking too long, we may be getting behind in some timed loops, causing them to pile up. 

A couple stats to keep in mind:
- the redis server is currently handling ~400ops/sec just to maintain the galaxy configuration. 
- listing the currently registered apps executes nearly 400 redis commands

**Comment by joeshaw** [comment]
listing all apps is O(n^2) now (at best) as it iterates over all the environments and then all the apps.

**Comment by jbardin** [comment]
either dropping redis, or rewriting config structures
