### ISSUE TITLE
[re]evaluate consul and etcd

### ISSUE THREAD

**Issue by jbardin** [litl/galaxy#235]
Re-evaluate Consul or etcd as a possible replacement for our redis config backend.  Our trees of versioned maps may not be easy to scale, and we haven't yet added multiple redis servers for availability.

With consul we would get a nameserver for free, and may be able to get rid of the dnsmasq galaxy domain hack.

**Comment by joeshaw** [comment]
For Consul we'd might still need to run a nameserver to forward requests: https://www.consul.io/docs/guides/forwarding.html

**Comment by jbardin** [comment]
yeah, unless the apps so lookups directly against the consul. Docker can also inject hosts file entries at runtime

**Comment by joeshaw** [comment]
thinking about this a little more... we could use `setcap` to give consul the ability to bind to port 53, and have it forward additional DNS requests to the real resolver. that way we wouldn't need either bind or dnsmasq

**Comment by jbardin** [comment]
I'd rather dodge the whole DNS issue entirely for now. Nothing currently really cares what the ip address of a service is, except for commander. All app access happens through shuttle.

I think having a `"hosts"` section in the app's config would be all we need; e.g.

```
{
  "hosts": [
    {
      "127.0.0.1": "apiary.galaxy"
    },
    {
      "127.0.0.1": "honeycomb.galaxy"
    }
  ]
}
```

Those entries could then be injected into the container by commander when it starts, and give us the same effect we have already.

I'd actually try to put this in now, except I don't see a nice way to do it without enumerating the environment variables and every VIRTUAL_HOST entry to guess at what an app needs.

**Comment by jbardin** [comment]
Looks like Consul is a good fit for what we want. If there's no objections, I'll close this and make a rough proposal with the other changes that go in tandem with replacing redis.

**Comment by joeshaw** [comment]
:+1:
