### ISSUE TITLE
Add services needed by apps to /etc/hosts

### ISSUE THREAD

**Issue by jbardin** [litl/galaxy#240]
The docker `--add-host` option put entries into the /etc/hosts inside the container. Use this instead of the dnsmasq resolver with the *.galaxy zone.

**Comment by joeshaw** [comment]
Can this be done dynamically after the container has started?  Otherwise it could be an issue if two services are interdependent.

**Comment by jbardin** [comment]
*.galaxy always resolves to the external IP of the local host (it gets redirected through shuttle), so IPs shouldn't need to change. 

I think one could technically exec into the running container and modify /etc/hosts if needed, but apps should generally know what other services they will depend on for the lifetime of that particular version.

**Comment by jbardin** [comment]
no clean way to do this currently, but we can bundle it with replacing the storage backend
