### ISSUE TITLE
Cannot deploy from private docker hub repository

### ISSUE THREAD

**Issue by zombor** [litl/galaxy#253]
Trying to deploy from a private repository I own. I've authenticated with docker and I can push/pull from it. However when running a commander deploy, I get:

```
root@power-nine:~/code/PowerNine-Delivery# commander app:deploy power-nine zombor/power-nine
Pulling image zombor/power-nine...
ERROR: error pulling image zombor/power-nine. Attempt 1: Error: image zombor/power-nine: not found
ERROR: error pulling image zombor/power-nine. Attempt 2: Error: image zombor/power-nine: not found
ERROR: error pulling image zombor/power-nine. Attempt 3: Error: image zombor/power-nine: not found
ERROR: unable to pull zombor/power-nine. Has it been released yet?
```

If I make this repository public, I'm able to deploy. I'm using Docker 1.7.0 with galaxy 0.6.0.

**Comment by joeshaw** [comment]
@zombor Thanks for the report.  Is this with the main docker hub registry?  We deploy from our own private registry but I don't think we've tested against a private repository on the main registry before.

**Comment by zombor** [comment]
Yes, from https://registry.hub.docker.com.

My docker auth is stored in `~/.docker/config.json`.

**Comment by jbardin** [comment]
The auth path needed some work anyway. I have a patch incoming for this...

**Comment by zombor** [comment]
The above commit seems to have resolved the problem:

```
root@power-nine:~/go/src/github.com/litl/galaxy# commander app:deploy power-nine zombor/power-nine
Pulling image zombor/power-nine...
Deployed zombor/power-nine.
```

**Comment by zombor** [comment]
I'm getting this same error again. I'm not sure what changed. If I make the repo public, it works fine. I still have my ~/.docker/config.json with the auth data in it.

**Comment by zombor** [comment]
Looks like the locked version of go-dockerclient didn't support ~/.docker/config.json. The above referenced PR fixes that.
