### ISSUE TITLE
columnize.SimpleFormat only returns one value

### ISSUE THREAD

**Issue by zombor** [litl/galaxy#256]
Whenever columnize.SimpleFormat is called, it assigns two variables, such as here: https://github.com/litl/galaxy/blob/master/commander/runtime.go#L70

However, this function only has a single return value: https://github.com/ryanuber/columnize/blob/master/columnize.go#L122

This causes the program to fail to compile.

**Comment by zombor** [comment]
Hmm, seems `make deps` depends on a really old version of columnize. Should this be updated?

**Comment by joeshaw** [comment]
Thanks a lot for the PR, updating our old version sounds good.
