### ISSUE TITLE
app:run output seems to be truncated

### ISSUE THREAD

**Issue by chrismrivera** [litl/galaxy#260]
I ran a command via commander app:run that appeared to exit without any indication of why.  Running the same command in the shell showed substantially more text, which contained an actual error message at the end.

**Comment by jbardin** [comment]
Here's a simple repro

    commander -env dev app:run apiary 'date; sleep 10; date'

The last `date` never make it to the console. 

This version exists early after ~20sec

    commander -env dev app:run apiary 'date; sleep 100; date'

**Comment by joeshaw** [comment]
Looks like a straightforward fix: switch `Stream` from `false` to `true` in the `AttachToContainerOptions` struct.
