### ISSUE TITLE
VersionID()/Image.ID is not deterministic across systems

### ISSUE THREAD

**Issue by jbardin** [litl/galaxy#276]
Galaxy relies on the image ID to identify running images, but that ID can change between running systems and docker versions preventing the app from running with:

> ERROR: Pulled image for registry/repo:latest does not match expected ID. Expected: a629b40202dc: Got: 10356cea8ac1

**Comment by joeshaw** [comment]
I think that's mainly a Docker 1.10 transition issue because it changed the image format and converts them on the fly during first run.

**Comment by jbardin** [comment]
I thought so too, but when I rebooted back into fresh docker 1.9 hosts some of the images still failed to run even though they were already running on docker 1.9 before the upgrade.

**Comment by jbardin** [comment]
Galaxy assumes the image ID is universal across systems, which it wasn't. Don't make galaxy depend on the image ID for anything other than forgoing a remote pull, but continue to log warning when the ID's don't match for now.

Closed by #279:
